[toolchain]
package_manager = "yarn"
anchor_version = "1.0.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
food_traceability = "HMB8KtLoTZcsCCQF8Bufjzf28XXjr21pKW3uENPLGrEW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
