[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
traza = "AwHQ1mST9r1xA7twQ5WpAbdcsbStJ2mtYijzL5C5sHV4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
